# .gitlab-ci.yml
stages:
  - cml_run

cml:
  stage: cml_run
  image: iterativeai/cml:0-dvc2-base1

  script:
    - pip3 install -r requirements.txt
    - python train.py

    - cat metrics.txt >> report.md
    - echo >> report.md
    - cml-publish confusion_matrix.png --md --title 'confusion-matrix' >> report.md
    - cml-send-comment report.md
